### ISSUE TITLE
How to visualize multi-classes

### ISSUE THREAD

**Issue by O2andsAnoxia** [pooya-mohammadi/yolov5-gradcam#1]
Hi, Thanks for your great work and the results look amazing. But I wonder that if it can visualize multi-classes by grad-cam whatever in classification or detection task.

**Comment by pooya-mohammadi** [comment]
@O2andsAnoxia 
Hi, it's my pleasure. As far as I'm aware, GradCam and other gradient-based visualization algorithms maximize the output of a single class, not altogether. If you have any different algorithms in mind, inform me, please.
