### ISSUE TITLE
The output image is darker than the input image 

### ISSUE THREAD

**Issue by wilile26811249** [pooya-mohammadi/yolov5-gradcam#2]
When I try to specify the img-size to 1280, the output image is darker than the input image.

**Comment by pooya-mohammadi** [comment]
@wilile26811249 
Yeah, that's because of the saliency map. At points in which no activation occurred, it's a dark layer. Also, for better visualization, a normalization operation is performed, resulting in a darker image.

**Comment by wilile26811249** [comment]
Thank you for your explain. I understand.
