### ISSUE TITLE
using CUDA, crashes script. 

### ISSUE THREAD

**Issue by anantsakhare** [pooya-mohammadi/yolov5-gradcam#27]
After using the Cuda as a device, it consumes GPU memory, there is a memory leak. 

causes due to score.backward(retain_graph=True)
@pooya-mohammadi

**Comment by ssbin0914** [comment]
@anantsakhare
Can you please tell me how you solved the memory leak problem? I get 'Cuda out of memory' error when I run grad-cam on bunch of images using CUDA.
