### ISSUE TITLE
why register_backward_hook() got the zero gradient

### ISSUE THREAD

**Issue by infochen** [pooya-mohammadi/yolov5-gradcam#6]
I took the gradcam for yolov3 and revise a little. 
I have no idea about why register_backward_hook() couldn't get the gradient. The register_forward_hook() is ok.
can you help me, thanks a lot.
![image](https://user-images.githubusercontent.com/100501692/158021281-b6f32de2-e94d-4ae7-b564-b0f94eb69102.png)

**Comment by infochen** [comment]
I used yolov3.pt for the yolov5-gradcam. The result like this:

![image](https://user-images.githubusercontent.com/100501692/158042215-7bd5ac0c-f9ed-40dd-9258-75ab74cc8ece.png)

I didn't change anything this time. I am confused about this situation

**Comment by infochen** [comment]
I figured out! I choose wrong layer before and the choosed layer' size must small.

**Comment by xiaobaidediyitian** [comment]
Hello, I have the same problem, may I ask how to solve it
