### ISSUE TITLE
heatmap visualization of the whole picture

### ISSUE THREAD

**Issue by zhaoxuyan** [pooya-mohammadi/yolov5-gradcam#8]
Thanks for your brilliant work!
How can I get a heatmap visualization of the whole picture? Please don't just visualize the box part?

**Comment by gabrispada** [comment]
Maybe just change this line
https://github.com/pooya-mohammadi/yolov5-gradcam/blob/8ae1f5801b27e0ddcdc9f527cb308d7e4793cf2a/main.py#L31
in this way:
`n_heatmat = (heatmap / 255).astype(np.float32)`
