### ISSUE TITLE
No heatmap using a different model

### ISSUE THREAD

**Issue by CBarrelet** [pooya-mohammadi/yolov5-gradcam#9]
Hi, thank you for your great job!

I tried to use a custom model, and even though the object is detected, the heatmap is basically empty. 

Do you know a workaround?

Thanks agin.

**Comment by pooya-mohammadi** [comment]
Hi @CBarrelet
Yolov5's model is modified every day. Maybe the model I have used is older and you are trying to test it with a newer model! 
But still I can't say without testing the actual model

**Comment by chentingkai** [comment]
> Hi, thank you for your great job!
> 
> I tried to use a custom model, and even though the object is detected, the heatmap is basically empty.
> 
> Do you know a workaround?
> 
> Thanks agin.

Hello, brother, have you solved this problem? I have the same problem. I would appreciate it if you could help me.

Looking forward to hearing from you.

**Comment by CBarrelet** [comment]
Hi @chentingkai, I found a workaround by using Yolo's visualization option. I added every features layer from each module and then scaled them to the image size by interpolation. The result seems visually ok.
Hope it could help!

**Comment by chentingkai** [comment]
> Hi @chentingkai, I found a workaround by using Yolo's visualization option. I added every features layer from each module and then scaled them to the image size by interpolation. The result seems visually ok. Hope it could help!

Thank you very much for your timely reply! I'm a novice in deep learning. Can you send me a copy of your executable code? My email address is tingkai1993@163.com . Thank you again for your selfless help.

**Comment by chentingkai** [comment]
> so it's easy to play around

Thank you very much for your timely reply!
